/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Acer
 */

package view; 

import config.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

public class shelter_hewan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(shelter_hewan.class.getName());

    /**
     * Creates new form shelter_hewan
     */
    public shelter_hewan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        gender_gender = new javax.swing.JComboBox<>();
        nama_hewan = new javax.swing.JTextField();
        nama_adopter = new javax.swing.JTextField();
        jenis_jenis = new javax.swing.JTextField();
        umur_umur = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rekap_data = new javax.swing.JTable();
        Update = new javax.swing.JButton();
        hapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setText("RUMAH HEWAN YEIRA");

        jLabel2.setText("Nama Hewan");

        jLabel3.setText("Nama Adopter");

        jLabel4.setText("Jenis");

        jLabel5.setText("Umur");

        jLabel6.setText("Gender");

        gender_gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jantan", "Betina" }));
        gender_gender.addActionListener(this::gender_genderActionPerformed);

        jenis_jenis.addActionListener(this::jenis_jenisActionPerformed);

        simpan.setText("Simpan");
        simpan.addActionListener(this::simpanActionPerformed);

        rekap_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Hewan", "Nama Adopter", "Jenis", "Umur", "Gender"
            }
        ));
        rekap_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rekap_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(rekap_data);

        Update.setText("Update");
        Update.addActionListener(this::UpdateActionPerformed);

        hapus.setText("Hapus");
        hapus.addActionListener(this::hapusActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(hapus)
                .addGap(18, 18, 18)
                .addComponent(Update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(simpan)
                .addGap(41, 41, 41))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nama_adopter)
                            .addComponent(umur_umur)
                            .addComponent(gender_gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jenis_jenis)
                            .addComponent(nama_hewan))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nama_hewan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nama_adopter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jenis_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(umur_umur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(gender_gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update)
                    .addComponent(hapus)
                    .addComponent(simpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:                                          
        String namaHewan = nama_hewan.getText();
        String namaAdopter = nama_adopter.getText();
        String jenis = jenis_jenis.getText();
        if (umur_umur.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Umur tidak boleh kosong!");
            return;
    }
        int umur = Integer.parseInt(umur_umur.getText());
        String gender = gender_gender.getSelectedItem().toString();

    try {
        Connection conn = config.Koneksi.getKoneksi();
        String sql = "INSERT INTO adopsi_hewan (nama_hewan, nama_adopter, jenis, umur, gender) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, namaHewan);
        ps.setString(2, namaAdopter);
        ps.setString(3, jenis);
        ps.setInt(4, umur);
        ps.setString(5, gender);
        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
        loadData(); 
        conn.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
    
    }                                      

    private void gender_genderActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void rekap_dataMouseClicked(java.awt.event.MouseEvent evt) {                                        
    int baris = rekap_data.getSelectedRow();
    DefaultTableModel model = (DefaultTableModel) rekap_data.getModel();
    
    nama_hewan.setText(model.getValueAt(baris, 1).toString());
    nama_adopter.setText(model.getValueAt(baris, 2).toString());
    jenis_jenis.setText(model.getValueAt(baris, 3).toString());
    umur_umur.setText(model.getValueAt(baris, 4).toString());
    gender_gender.setSelectedItem(model.getValueAt(baris, 5).toString());
        // TODO add your handling code here:
    }                                       

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        int baris = rekap_data.getSelectedRow();

if (baris == -1) {
    JOptionPane.showMessageDialog(
        this,
        "Pilih data yang mau diupdate dulu!"
    );
    return;
}

DefaultTableModel model =
        (DefaultTableModel) rekap_data.getModel();

int id = Integer.parseInt(
        model.getValueAt(baris, 0).toString()
);

String namaHewan   = nama_hewan.getText();
String namaAdopter = nama_adopter.getText();
String jenis       = jenis_jenis.getText();

int umur = Integer.parseInt(
        umur_umur.getText()
);

String gender = gender_gender
        .getSelectedItem()
        .toString();

try {
    Connection conn = config.Koneksi.getKoneksi();

    String sql =
        "UPDATE adopsi_hewan SET " +
        "nama_hewan=?, " +
        "nama_adopter=?, " +
        "jenis=?, " +
        "umur=?, " +
        "gender=? " +
        "WHERE id_hewan=?";

    PreparedStatement ps =
            conn.prepareStatement(sql);

    ps.setString(1, namaHewan);
    ps.setString(2, namaAdopter);
    ps.setString(3, jenis);
    ps.setInt(4, umur);
    ps.setString(5, gender);
    ps.setInt(6, id);

    ps.executeUpdate();

    JOptionPane.showMessageDialog(
        this,
        "Data berhasil diupdate!"
    );

    loadData();
    conn.close();

} catch (Exception e) {

    JOptionPane.showMessageDialog(
        this,
        "Error: " + e.getMessage()
    );
}
    }                                      

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        int baris = rekap_data.getSelectedRow();

if (baris == -1) {
    JOptionPane.showMessageDialog(this, "Pilih data yang mau dihapus dulu!");
    return;
}

DefaultTableModel model = (DefaultTableModel) rekap_data.getModel();
int id = Integer.parseInt(model.getValueAt(baris, 0).toString());

int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin mau hapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

if (konfirmasi == JOptionPane.YES_OPTION) {
    try {
        Connection conn = config.Koneksi.getKoneksi();
        String sql = "DELETE FROM adopsi_hewan WHERE id_hewan=?";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setInt(1, id);
        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
        loadData();
        conn.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
    }                                     

    private void jenis_jenisActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new shelter_hewan().setVisible(true);
            }
        });
    }
    private void loadData() {

    DefaultTableModel model = (DefaultTableModel) rekap_data.getModel();
    model.setRowCount(0);

    try {

        Connection conn = Koneksi.getKoneksi();

        String sql = "SELECT * FROM adopsi_hewan";

        Statement stmt = conn.createStatement();

        ResultSet rs = stmt.executeQuery(sql);

        while (rs.next()) {

            Object[] baris = {
                rs.getInt("id_hewan"),
                rs.getString("nama_hewan"),
                rs.getString("nama_adopter"),
                rs.getString("jenis"),
                rs.getInt("umur"),
                rs.getString("gender")
            };

            model.addRow(baris);

        }

        rs.close();
        stmt.close();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());

    }

}
    
    

    // Variables declaration - do not modify                     
    private javax.swing.JButton Update;
    private javax.swing.JComboBox<String> gender_gender;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jenis_jenis;
    private javax.swing.JTextField nama_adopter;
    private javax.swing.JTextField nama_hewan;
    private javax.swing.JTable rekap_data;
    private javax.swing.JButton simpan;
    private javax.swing.JTextField umur_umur;
    // End of variables declaration                   
}
